-- Migración 0013: "Ecos del océano" (antes "Pensamiento del día"), ahora en la base para que la dueña
-- los cargue, edite, oculte y borre desde /admin/ecos. Hasta acá eran un arreglo fijo en el código
-- (`src/datos/pensamientos.ts`); esta misma migración siembra los 376 de ese arreglo, en su orden.
--
-- `numero` fija el orden de la rotación (el front recorre los publicados ordenados por `numero`): lo
-- da la base al insertar, nunca el cliente. Cualquiera lee los publicados (no es contenido premium);
-- la admin lee todos y es la única que escribe (RLS con `es_admin()`), nunca `using (true)`.

begin;

create table public.ecos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated always as identity unique,
  texto text not null,
  publicado boolean not null default true,
  creado_en timestamptz not null default now(),
  constraint ecos_texto_largo check (char_length(btrim(texto)) between 1 and 500)
);
alter table public.ecos enable row level security;

revoke all on public.ecos from anon, authenticated;
grant select on public.ecos to anon, authenticated;
grant insert (texto, publicado), update (texto, publicado), delete on public.ecos to authenticated;

create policy ecos_lectura_publica on public.ecos
  for select to anon, authenticated
  using (publicado);

create policy ecos_admin on public.ecos
  for all to authenticated
  using ((select public.es_admin()))
  with check ((select public.es_admin()));

-- Los 376 del documento «365 pensamientos» de la dueña, en su orden.
insert into public.ecos (texto) values
  ('Libero el pasado y vivo el presente.'),
  ('Estoy dispuesto a crecer y a cambiar: Cada momento me ofrece una maravillosa oportunidad para ser más yo mismo.'),
  ('Elijo reconocer la magnificencia de mi ser.'),
  ('Todo me lleva a experiencias gratificantes y satisfactorias. Creo para mí una vida llena de recompensas.'),
  ('Estoy muy bien organizado. La vida es sencilla y fácil.'),
  ('Siempre me resulta fácil cambiar. Soy flexible y dúctil.'),
  ('Aquello que doy es lo que recibo de vuelta. Como doy sólo bondad, sólo bondad me devuelven los demás.'),
  ('Quiero aprender a amarme. Estoy dispuesto.'),
  ('Hago cosas nuevas y comienzo fascinantes emprendimientos.'),
  ('Me siento a salvo en el ritmo y en el transcurso de una vida siempre cambiante.'),
  ('El pasado no tiene ningún poder sobre mí. Sé que es pasado y vivo únicamente en el Ahora.'),
  ('Veo claramente mis hábitos limitantes. Efectúo cambios sin sentir turbación ni culpa.'),
  ('Con alegría y facilidad paso todas las dificultades.'),
  ('Dondequiera que voy mi experiencia es de amor. Mi vida está llena de seres que me aman y yo les expreso a todos mi amor.'),
  ('Miro más allá de las limitaciones de los demás y acepto a cada persona como un ser único y maravilloso.'),
  ('Estoy en paz con mi sexualidad. Me acepto sin reservas, con amor y comprensión.'),
  ('Sé que el proceso de la vida me traerá el supremo bien.'),
  ('Reconozco que la toma de conciencia es el primer paso para sanar o cambiar. Cada día lo comprendo mejor.'),
  ('Mis pensamientos son creativos. Tengo nuevas intuiciones y descubro nuevas formas de contemplar mi mundo.'),
  ('Las respuestas que hay en mi interior afloran fácilmente a mi conciencia.'),
  ('Los demás no están equivocados: son diferentes. Todos somos uno.'),
  ('La efectividad del poder está siempre en el momento presente. Vivo el presente, libre y feliz.'),
  ('Soy totalmente capaz en todo momento. Me acepto, y creo paz en mi mente y en mi corazón.'),
  ('Ningún trabajo está por debajo o por encima de mí. Si es necesario hacer algo, lo hago.'),
  ('Asumo la total responsabilidad de cada uno de los aspectos de mi vida.'),
  ('Amo mi cuerpo. Con cada año que pasa me siento más relajad@ y atractiv@.'),
  ('Me merezco lo mejor y lo acepto ahora mismo. Todos mis deseos y necesidades se ven satisfechos sin tener que pedirlos.'),
  ('Expreso abierta y libremente mi creatividad.'),
  ('Estoy dispuesto a renunciar a los arraigados hábitos que crean condiciones negativas en mi vida.'),
  ('Todo aquello que deseo, lo recibo. Encuentro satisfacción en todos los ámbitos de mi vida.'),
  ('Soy mi mejor amigo y amo todo lo que veo en mí.'),
  ('Coopero con la vida. Es la estación inactiva. Aprovecho este tiempo para entrar a mi interior y calmar mi mente.'),
  ('Sé hablar en mi favor. Empleo mi poder.'),
  ('El amor es siempre la respuesta para sanar en cualquier aspecto. Me amo exactamente tal como soy.'),
  ('Sé expresar mis emociones en todo momento, de forma sincera y abierta.'),
  ('Mi cuerpo refleja mi estado de ánimo. Soy una persona sana e íntegra.'),
  ('Mi vida refleja cada uno de mis pensamientos. Como estos son siempre positivos, la vida me brinda sólo buenas experiencias.'),
  ('Siempre llego a tiempo, fácilmente y sin esfuerzo.'),
  ('Mi mente es poderosa. Ella crea mis experiencias. Mi capacidad de crear el bien en mi vida no tiene límites.'),
  ('No necesito ganarme el amor. Me lo merezco simplemente porque existo.'),
  ('Mi capacidad creativa y mis talentos fluyen a través de mí y se expresan de maneras profundamente satisfactorias.'),
  ('Esté donde esté, me encuentro a salvo. Yo creo mi propia seguridad.'),
  ('Estoy en el lugar y el momento perfectos, haciendo lo correcto.'),
  ('Cada experiencia de mi vida es una oportunidad para crecer.'),
  ('El amor que brota de mi corazón me inunda, limpiando y sanando todo mi cuerpo y mis emociones.'),
  ('Cuanto más me amo, más amor siento por los demás. Cuanto más amor doy, más amor tengo para dar.'),
  ('Todas mis relaciones son armoniosas: En todo momento sólo veo armonía a mi alrededor.'),
  ('Abro mi conciencia a la expansión de la vida. Hay espacio de sobra para que yo pueda crecer y cambiar.'),
  ('Todo lo que emprendo es un éxito. Como un imán atraigo hacia mí toda clase de prosperidad.'),
  ('Míos son la seguridad y el poder. Cada decisión que tomo es la más acertada para mí.'),
  ('Amo a quien soy, lo que soy y lo que hago.'),
  ('El pasado es pasado y no se puede cambiar. Este momento presente es el único que puedo experimentar.'),
  ('Estoy en paz con los elementos de la naturaleza. No hay “buen” tiempo ni “mal” tiempo: sólo es mi reacción ante él.'),
  ('Me afirmo en la verdad, y vivo y me muevo en la alegria.'),
  ('Mis buenos pensamientos crean mi mundo. Escojo con esmero mis pensamientos.'),
  ('Confío en mí. Sé que la vida me sustenta y me protege.'),
  ('Me pagan muy bien por hacer algo que me agrada. Sé que puedo tener todo el éxito que decida tener.'),
  ('Estoy dispuesto a descubrir en qué aspectos necesito cambiar.'),
  ('Hoy hago una limpieza en mi casa mental para dejar lugar a nuevos pensamientos positivos.'),
  ('Soy una magnífica y divina expresión de la vida. El amor me rodea y me protege.'),
  ('Este día me trae experiencias fabulosas. Asumo la responsabilidad de mis experiencias.'),
  ('Nada me puede dañar porque sé quién soy: un ser único y maravilloso. La alegría me invade. Sé lo que valgo.'),
  ('Me infundo ánimo con cariño y entusiasmo.'),
  ('Pongo atención a los mensajes de mi cuerpo. Todo mi cuerpo respira salud.'),
  ('Me río de mí y de la vida, y nada me puede dañar.'),
  ('En todas mis experiencias procedo con sabiduría, amor y naturalidad.'),
  ('Estoy abierto y receptivo a nuevas fuentes de ingresos.'),
  ('Me entusiasma la vida. Todo en mí es energía y optimismo.'),
  ('Cada momento me ofrece una nueva y maravillosa oportunidad de ser más quien soy.'),
  ('Hoy elijo liberarme de todos los resentimientos y heridas.'),
  ('En todo momento, sólo veo armonía a mi alrededor. Estoy a salvo y seguro.'),
  ('Dondequiera que voy, mi experiencia es de amor.'),
  ('Los cumplidos son ofrendas de prosperidad. Los acepto con gracia y de buena gana.'),
  ('Mi parte masculina y mi parte femenina están en perfecto equilibrio y total armonía. Me siento a gusto en mi cuerpo.'),
  ('Pienso cosas positivas porque cada célula de mi cuerpo responde a cada idea que pienso y a cada palabra que digo.'),
  ('Miro dentro de mí para encontrar mis tesoros.'),
  ('Soy consciente de que lo que no quiero cambiar es exactamente lo que más necesito cambiar.'),
  ('Todos cambiamos, y yo acepto que todo el mundo cambie.'),
  ('Alegría, alegría, alegría. Con amor permito que la alegría inunde mi mente, mi cuerpo y mis experiencias.'),
  ('Confío en mi guía interior. Cualquier cosa que emprenda será un éxito.'),
  ('Siento una amorosa comprensión por mis padres.'),
  ('Hoy es un día maravilloso porque he decidido que lo sea.'),
  ('Acepto la salud perfecta como el estado natural del ser.'),
  ('Mi entendimiento es claro, y estoy dispuesto a cambiar con los tiempos.'),
  ('Yo creo mi propia realidad, y elijo a todas las personas que forman parte de ella.'),
  ('El poder interior que respira en mi cuerpo es el mismo poder que me proporciona todo lo que necesito, con naturalidad.'),
  ('Mi cuerpo quiere mantenerse activo y sano. El ejercicio es un placer para mí.'),
  ('Soy libre de tener pensamientos maravillosos. Yo controlo mi propia mente.'),
  ('El amor fluye a través de todo mi ser: toca a todos aquellos a quienes conozco y me encamina hacia una mayor compasión.'),
  ('Todo lo que busco lo tengo ya dentro de mí.'),
  ('Perdono a los demás, y ahora creo mi propia vida tal como quiero que sea.'),
  ('Voy más allá de las limitaciones del pensamiento humano y me pongo del lado de la infinita Mente, donde todo es posible.'),
  ('La vida es eterna y rebosa de entusiasmo. Soy un ser eterno.'),
  ('El tiempo de sembrar semillas nuevas se convierte en jubilosa expectación. Sé que todo ocurre en el momento perfecto.'),
  ('Supero las limitaciones de mis padres y estoy a salvo. Soy libre de ser yo mismo.'),
  ('Soy tolerante y compasivo. Amo a todo el mundo, incluido yo mismo.'),
  ('Sólo digo palabras positivas, constructivas y amables.'),
  ('Ahora me libero de toda lucha y estoy en paz.'),
  ('La Vida me creó para que me realizara. Hoy libero todas las expectativas. Sé que la Vida cuidará de mí.'),
  ('No hay persona, lugar ni cosa que tenga poder alguno sobre mí, porque en mi mente sólo pienso yo.'),
  ('Cada experiencia que tengo me beneficia. Estoy en un proceso de cambios positivos.'),
  ('Mi cuerpo representa la perfección. Estoy sano y palpitante de energía.'),
  ('Me elevo por encima de toda limitación. La Divinidad me inspira y me guía.'),
  ('Estoy dotado mental y emocionalmente para disfrutar del amor y la prosperidad. Todo lo que hago me satisface plenamente.'),
  ('Soy una persona maravillosa. El sentido del humor y la alegría contribuyen a mi bienestar total.'),
  ('La vida sólo me ofrece buenas experiencias. Estoy abierto a lo nuevo y cambiante.'),
  ('Siempre soy capaz de tomar la decisión correcta. Reconozco mi capacidad intuitiva.'),
  ('Cada cambio que hay en mi vida puede elevarme a un nuevo plano de entendimiento.'),
  ('Me alegran mucho los éxitos de los demás. Hay en abundancia para todos.'),
  ('En mi vida se sucede un milagro tras otro. Acepto las curaciones milagrosas en mi vida y en mi mundo.'),
  ('Ninguna forma de pensar pasada me limita. Espero el futuro con ilusión y alegría.'),
  ('Aquí y ahora opto por expulsar de mi mente y de mi vida todo pensamiento negativo, destructivo o aterrador.'),
  ('Dentro de mí veo un ser lleno de amor y de belleza. Me infunde seguridad mirar en mi interior.'),
  ('Mi vida y todo lo que me rodea mejoran día tras día. Me voy acercando a mi mayor bien.'),
  ('Cuando creo paz, equilibrio y armonía en mi mente, eso es lo que encuentro en mi vida.'),
  ('Todos somos una familia, y el planeta es nuestro hogar.'),
  ('Me concentro en pensamientos positivos porque las ideas que tengo y las palabras que digo crean mis experiencias.'),
  ('Me siento eufórico de felicidad, en armonía con la totalidad de la vida.'),
  ('En mis relaciones siempre hay una maravillosa armonía. La persona a quien ahora busco también me busca.'),
  ('Utilizo mi poder con acierto. Soy fuerte. Estoy a salvo. Todo está bien.'),
  ('La Vida me sustenta en cada tramo del camino. Me alimenta, me viste, me proporciona hogar y cariño.'),
  ('Siento una energía desbordante. Me siento lleno de vida y dinamismo.'),
  ('El Universo apoya plenamente todo lo que elijo pensar y creer. Pienso cosas positivas.'),
  ('Soy una persona digna de amor. Soy un ser maravilloso. Soy amado.'),
  ('La nueva vegetación me llena de alegría. El despertar de la vida, es una delicia contemplarla.'),
  ('Siempre se me brindan nuevas y preciosas oportunidades.'),
  ('Hoy acepto y vivo la abundante Vida que me ofrece el Universo.'),
  ('Elegí a mi madre porque ella era exactamente la persona que yo necesitaba para hacerme capaz de aprender y de crecer.'),
  ('Mi corazón está abierto. Estoy dispuesto a abandonar toda resistencia.'),
  ('Los cambios pueden empezar en este momento. Estoy dispuesto.'),
  ('Aprecio y valoro todo lo que hago. Valgo tal como soy.'),
  ('Es mi derecho vivir con plenitud y en libertad.'),
  ('Acepto que mis ingresos aumenten constantemente. Llevo una vida cómoda y hermosa.'),
  ('Reconozco a mi cuerpo como un buen amigo.'),
  ('En mi mundo, el poder creativo soy yo. Me expreso de la forma más creativa posible.'),
  ('Procedente de canales esperados e inesperados, el bien inunda hoy mi vida.'),
  ('El amor es la cura milagrosa. Mi amor por mí mismo hace milagros en mi vida.'),
  ('Tengo el espacio vital perfecto: es seguro y está lleno exclusivamente de pensamientos de amor.'),
  ('Soy uno con el poder y la sabiduría del Universo. Tengo todo lo que necesito.'),
  ('Mi capacidad de crear el bien en mi vida no tiene límites.'),
  ('Mis pensamientos felices crean mi mundo feliz.'),
  ('Respiro libre y plenamente. Confío en el proceso de la vida.'),
  ('Poseo mi propio conjunto de talentos y capacidades.'),
  ('Hoy libero mi rabia de manera positiva. Me amo y me valoro.'),
  ('Mantengo mis pensamientos centrados en lo que deseo experimentar.'),
  ('Estoy dispuesto a cambiar todos mis hábitos de crítica.'),
  ('En igual proporción se me ha dotado de amor, armonía y dicha. En perfecto equilibrio acojo la vida.'),
  ('El Océano de la Vida es pródigo al distribuir sus bienes. En todas partes me aguardan excelentes oportunidades.'),
  ('Mi visión es clara. Ahora me creo una vida que me complace mirar.'),
  ('Dejo fluir mi amor libremente. Mi provisión de amor es infinita.'),
  ('Doy a mi cuerpo alimentos y bebidas nutritivos, y lo ejercito de manera agradable y placentera.'),
  ('Estoy en paz con mi mundo. Estoy en paz conmigo.'),
  ('Estoy dispuesta@ a liberar la necesidad de ser indigna@. Empiezo a convertirme en todo aquello para lo cual fui creada@.'),
  ('Me siento a gusto con todas las personas que conozco. Todas mis relaciones son sanas y alentadoras.'),
  ('Me perdono y me libero.'),
  ('Agradezco a los demás la bondad que me demuestran. Los elogios y la gratitud me desbordan.'),
  ('Estoy abierto y receptivo al amor. En cada persona, incluido yo, busco lo positivo; en todas veo la perfección.'),
  ('Comprendo y amo a todo el mundo. El amor me hace sentir a gusto.'),
  ('Encuentro elogio y alegría en todo lo que digo y hago.'),
  ('Mi vida desborda de alegría y mejora constantemente.'),
  ('Estoy abierto y receptivo a todo el bien y la abundancia del Universo.'),
  ('Yo creo mis propias experiencias. Como amo y me apruebo a mí y a los demás, mis experiencias son cada vez mejores.'),
  ('Todos mis amigos entienden mis necesidades. Tengo muchísimos amigos que me aman.'),
  ('Me hago un tiempo para hacer las cosas que me gustan. Salgo y experimento la vida de una forma nueva.'),
  ('Todos mis deseos y necesidades se ven satisfechos sin que tenga siquiera que pedirlo. Todo está bien en mi mundo.'),
  ('Todos hacemos lo mejor que podemos hacer con el entendimiento, el conocimiento y la información que tenemos.'),
  ('Mi mente es un instrumento que puedo usar de la manera que me apetezca.'),
  ('Nuevas y felices ideas circulan libremente dentro de mí.'),
  ('El perdón es un regalo que me hago a mi mismo. Se me hace fácil y gratificante perdonar.'),
  ('Yo respeto a mis padres, y ellos, a su vez, me respetan.'),
  ('Todas mis experiencias son oportunidades de aprender y crecer.'),
  ('Me considero una persona hermosa, apreciada y digna de ser amada. Me enorgullezco de ser quien soy.'),
  ('Me acepto plenamente y creo paz en mi mente y mi corazón.'),
  ('Merezco disfrutar de la vida. Pido lo que deseo y lo acepto con placer y alegría.'),
  ('Mi hogar colma todos mis deseos y necesidades y yo lo lleno con la vibración del amor.'),
  ('Hoy libero mis dudas y miedos destructivos.'),
  ('A la gente le encanta estar conmigo, y a mí me encanta estar con la gente.'),
  ('Es mi derecho participar de la abundancia y la prosperidad de este mundo.'),
  ('Soy uno con el Universo y la totalidad de la vida. Puedo aprender y crecer sin temor.'),
  ('Las dificultades ya no me amargan. Resuelvo todos los problemas con facilidad.'),
  ('Soy un canal abierto para las ideas creativas.'),
  ('Soy una persona competente y organizada. Mi eficiencia es más que suficiente para realizar mi trabajo.'),
  ('Con amor y júbilo acepto mi sexualidad y mi manera de expresarla.'),
  ('Soy capaz de afrontar y llevar a buen fin cualquier cosa que se me presente.'),
  ('Elijo experimentar la dulzura de la vida.'),
  ('Soy una persona firme. Continúo lo empezado y me doy aliento con amor.'),
  ('Mi vida mejora continuamente.'),
  ('Declaro mi independencia. Todas las respuestas que necesito están dentro de mí. Confío en mi propia sabiduría interior. Confío en mí para tomar las mejores decisiones en todo lo que haga.'),
  ('El amor de mi corazón inunda alegremente todo mi cuerpo.'),
  ('Mi vida refleja el bien, y solo bien recibo a cambio. Soy la serena y la tranquila expresión de la vida.'),
  ('Siempre trabajo con y para personas maravillosas. Me encanta mi trabajo.'),
  ('Ahora estoy libre del pasado. La libertad es mi derecho divino.'),
  ('Mi mente y mi cuerpo están perfectamente equilibrados. Soy un ser armonioso.'),
  ('Con amor acepto mis decisiones, sabiendo que tengo la libertad de cambiar.'),
  ('Constantemente tengo nuevas intuiciones y hallo nuevas maneras de ver el mundo.'),
  ('Avanzo con seguridad y soltura, sabiendo que todo está bien en mi futuro.'),
  ('Soy una persona cada vez más simpática. Los demás me consideran afectuosa y capaz de perdonar.'),
  ('Soy responsable de todas mis experiencias.'),
  ('La gente me respeta, y valora mucho todo lo que hago.'),
  ('Irradio amor y simpatía. Soy una persona hermosa y todo el mundo me ama.'),
  ('Mantengo los ojos bien abiertos para no dejar pasar mis mejores oportunidades.'),
  ('Ahora atraigo a nuevos amigos y amigas, personas interesantes, amables, responsables, tolerantes, divertidas y generosas.'),
  ('Sé que la Sabiduría y la Prudencia Divinas me protegen en todo momento.'),
  ('¡Amo la vida! Espero con ilusión cada momento.'),
  ('Todos mis problemas proceden de pensamientos que me limitan. Resuelvo mis problemas escogiendo pensamientos positivos.'),
  ('Mi hogar es un refugio de paz. En todos sus rincones pongo amor, y me responde con calor y comodidad.'),
  ('Expreso mis emociones de forma alegre y positiva.'),
  ('Mi riqueza no tiene límites. El amor, la risa y las comodidades me pertenecen.'),
  ('Agradezco a la vida su generosidad. Soy muy afortunado.'),
  ('Dejo todo control en manos del Universo. Estoy en paz conmigo y con la vida.'),
  ('Crezco más allá de las limitaciones de mis padres y vivo mi propia vida. Ahora es mi turno.'),
  ('Me libero, y libero a todas las personas que forman parte de mi vida, de las viejas heridas del pasado.'),
  ('El bienestar es el estado natural de mi cuerpo. Yo sólo pienso en el bienestar.'),
  ('Mi vida es un gozo. La Mente Divina me guía hacia el logro de mis objetivos.'),
  ('Tengo todo el éxito que yo decido tener.'),
  ('Respeto y protejo mi cuerpo porque me importa mi salud.'),
  ('Abro mi corazón y canto las alegrías del amor.'),
  ('La paz y la armonía divinas me rodean y habitan en mi interior. Confío en el proceso de la vida.'),
  ('Estoy en total armonía con mi entorno: el sol, la luna, los vientos, la lluvia y la tierra.'),
  ('Contemplo mi vida y sólo veo belleza. La naturaleza está en calma y en paz. Es un momento para la reflexión.'),
  ('Ahora irradio salud, felicidad, prosperidad y paz espiritual.'),
  ('Voy más allá de mis viejas limitaciones, y me expreso de forma libre y creativa.'),
  ('Confío en mi Yo Superior, y escucho mi Voz Interior con amor.'),
  ('Me abro a la sabiduría interior, sabiendo que en este Universo sólo hay Una Inteligencia.'),
  ('Cuando escucho a mi yo interior recibo las respuestas que necesito.'),
  ('Expresar las emociones es curativo. Puedo ser vulnerable sin temor.'),
  ('Abro mi conciencia a todas las maravillosas posibilidades de la vida.'),
  ('Me encuentro a salvo. Sólo se trata de un cambio.'),
  ('Reconozco que mi cuerpo es un mecanismo asombroso y magnífico. Es un privilegio vivir en él.'),
  ('En mi interior veo a un ser magnífico, sabio y hermoso. Amo lo que veo en mí.'),
  ('Todo lo que necesito saber se me revela.'),
  ('Cuando me amo verdaderamente, todo funciona en mi vida.'),
  ('Soy responsable. Ahora recupero mi propio poder.'),
  ('Me siento bien siendo tal como soy. En todo momento me apruebo y me acepto.'),
  ('Me relajo y reconozco mi propio valor.'),
  ('Vaya donde vaya, viajo segur@. En mis viajes siempre encuentro gente amable que me ayuda.'),
  ('Libero la necesidad de culparme y de culpar a los demás.'),
  ('Las personas que hay en mi vida son en realidad mis espejos. Mi mundo es un lugar seguro y acogedor.'),
  ('El día de hoy es un peldaño hacia una nueva conciencia y una mayor gloria.'),
  ('Estoy muy bien. La vida es fácil y dichosa.'),
  ('La libertad y el cambio están en el aire. Desecho las ideas viejas.'),
  ('Mi cuerpo me lleva a todas partes con facilidad y sin esfuerzo.'),
  ('Me rodeo de personas que me aman y que sólo ven lo bueno, en mí y en mi entorno.'),
  ('Inspiro y, con mi aliento envío vida a mis ojos, para verlo todo con comprensión y compasión.'),
  ('Soy uno con el Poder que me ha creado. De ese poder participo para crear mis circunstancias.'),
  ('El trabajo y la diversión en mi vida están en feliz equilibrio.'),
  ('De la Inteligencia Divina me vienen todas las ideas que necesito.'),
  ('Veo lo mejor en los demás, y les ayudo a sacar a la luz sus mejores cualidades.'),
  ('Comprendo la infancia de mis padres. Ahora sé que los escogí porque eran perfectos para lo que yo tenía que experimentar.'),
  ('He sido cread@ para triunfar, y agradezco el éxito que hoy tengo.'),
  ('Cuanto más ayudo a los demás, más aumenta mi prosperidad. Donde yo estoy, todo el mundo gana.'),
  ('Despierto a nuevas energías. Es tiempo de cosecha. Recogemos los frutos de lo sembrado. Me siento en armonía.'),
  ('Creo paz en mi mente y confío en mi sabiduría interior.'),
  ('Mi trabajo es estimulante, divertido y muy satisfactorio. En él utilizo mis talentos y capacidades, mi creatividad.'),
  ('Las personas, los lugares y las cosas de este planeta están conectados entre sí con amor. Me siento a gusto en el Universo.'),
  ('Cada puente que atravieso me lleva a un plano de realización más elevado.'),
  ('Dondequiera que estoy, escojo la armonía y la amable comunicación con los demás.'),
  ('Aprecio todo lo que hago. Soy la persona más importante de mi vida.'),
  ('Con alegría mantengo a mi niño interior seguro en el centro de mi ser. Lo amo y lo cuido.'),
  ('Cada momento es un nuevo comienzo. Mi vida es hermosa.'),
  ('Soy una persona compasiva y comprensiva. Perdono y olvido.'),
  ('Con mi amorosa actitud ayudo a crear un mundo donde amarnos los unos a los otros no implique ningún peligro.'),
  ('Sigo a mi estrella interior y soy un ejemplo resplandeciente de amor y de luz.'),
  ('Todo lo que pienso que está “mal” en mí lo transformo en afirmaciones positivas.'),
  ('Inhalo el precioso aliento de la vida y dejo que mi cuerpo, mi mente y mis emociones se relajen.'),
  ('Llevo adelante mi vida con facilidad y alegría.'),
  ('Me alegro de adaptarme con tanta facilidad al flujo y reflujo de mi vida.'),
  ('Soy dulce, bondados@ y paciente conmigo mism@. Los demás reflejan el amor que siento por mí.'),
  ('Perdono con amor y libero el pasado.'),
  ('Tengo un cuerpo sano y feliz. Mi cuerpo está siempre trabajando por una salud óptima.'),
  ('Hoy es el futuro que creé ayer.'),
  ('Me alegro de saber que cuento con el poder de mi mente para usarlo de la manera que yo decida.'),
  ('En mi vida todo funciona, ahora y siempre.'),
  ('Mis pensamientos son apacibles, serenos y centrados.'),
  ('El bien me llega de todas partes, de todas las personas y de todas las cosas. Me siento feliz de ser quien soy.'),
  ('Las puertas de la sabiduría y el conocimiento están siempre abiertas para mí.'),
  ('Constantemente tengo nuevas intuiciones. Mi futuro es magnífico.'),
  ('Me siento a salvo viviendo. La vida siempre me proporciona lo que necesito. Todo está bien.'),
  ('El Océano de la Vida es pródigo con su abundancia. Siempre que necesito algo, sé que lo tendré.'),
  ('El perdón me hace libre y liger@. Perdono a todo el mundo.'),
  ('Las decisiones que tome durante todo este día serán las correctas. Sólo deseo aquello que ha de proporcionarme el mayor bien.'),
  ('Las hojas caen del árbol en el momento oportuno. Así caen de mí las creencias y los hábitos que ya no me sirven.'),
  ('Dejo atrás mis viejas creencias negativas. Las nuevas me serán más útiles.'),
  ('Cada uno de mis actos atrae la abundancia. Soy un imán para la Prosperidad Divina.'),
  ('Me doy permiso para ser todo lo que puedo ser. Me merezco lo mejor.'),
  ('Me abrazo con amor y compasión. Acepto mi forma de ser, especial y única.'),
  ('Me siento con fuerzas y capacidad para todas las situaciones.'),
  ('Me amo y me recompenso con pensamientos elogiosos.'),
  ('Libero la necesidad de culpar a nadie. Acepto a los demás tal como son.'),
  ('Este es un nuevo día. Soy un nuevo yo.'),
  ('Todo me sucede en el momento y el lugar perfectos. A cada momento se produce la correcta acción divina.'),
  ('Me complazco en mi propia expresión de la vida. Soy un ser perfecto tal como soy.'),
  ('Convierto cada experiencia en una oportunidad.'),
  ('Con toda confianza puedo ser lo suficientemente flexible para comprender los puntos de vista de los demás.'),
  ('Tengo el derecho divino de obtener satisfacción en todos los aspectos de la vida. Soy dign@ del éxito.'),
  ('Navego plácidamente a través de nuevas experiencias, nuevos rumbos y nuevos cambios.'),
  ('Fácilmente me deshago de lo que ya no necesito.'),
  ('Cuento con el apoyo total y absoluto del Universo.'),
  ('La relajación sirve a mi cuerpo como un tiempo de reparación y rejuvenecimiento. Cuanto más me relajo, mejor salud tengo.'),
  ('Se me hace fácil defender mis puntos de vista.'),
  ('Cada experiencia que tengo me guía hacia una mayor capacidad de comprensión.'),
  ('Mis ingresos aumentan constantemente.'),
  ('Todo problema tiene su solución. Para mí, aprender es fácil y divertido.'),
  ('Estoy dispuest@ a crecer y a enfrentarme con mis sentimientos.'),
  ('Los demás me respetan porque yo me respeto.'),
  ('De mi vida sólo desaparece aquello que ya no necesito. Todo lo que me rodea tiene una utilidad.'),
  ('Espero con ilusión las aventuras del día.'),
  ('La vida me inspira confianza, seguridad y alegría. Sólo bien viene a mí y sólo bien emana de mí.'),
  ('Mi corazón está abierto. Me expreso con palabras afectuosas.'),
  ('Me complazco en lo que tengo y sé que siempre me esperan experiencias nuevas. El Universo da y yo recibo.'),
  ('Tengo opciones ilimitadas sobre lo que puedo pensar. Mi mente se siente libre y ligera.'),
  ('Hoy estoy dispuest@ a reconocer mi belleza y mi magnificencia.'),
  ('Es mi derecho expresarme creativamente de formas enormemente estimulantes. Hoy lo pasaré muy bien.'),
  ('Bendigo mi maravillosa vida. Con alegría, placer y gratitud acepto todo el bien que me ofrece la vida.'),
  ('Agradezco todo el bien, todo lo que con amor se me facilita.'),
  ('Hoy cuido amorosamente de mi cuerpo, de mi mente y de mis emociones.'),
  ('Continuamente encuentro nuevas maneras de mirar mi mundo. En todas partes veo belleza.'),
  ('Bendigo y deseo prosperidad a los demás, que a su vez me bendicen y me desean prosperidad.'),
  ('Veo venir un mundo de paz y abundancia. Siento la armonía y la unidad entre las naciones, y contribuyo a crearlas.'),
  ('Hay tiempo y espacio para todo lo que deseo hacer.'),
  ('Estoy rodeado de personas cariñosas y se me hace fácil expresar mi amor a los demás.'),
  ('Sé que la vida es maravillosa. En mi futuro sólo veo cosas buenas.'),
  ('Amo a mi familia y a mi hogar. Ellos me proporcionan sustento, calor y seguridad.'),
  ('Cuento con que mi vida será buena y dichosa, y lo es.'),
  ('Mis pensamientos de paz crean mi mundo de paz.'),
  ('Abro mi conciencia a la expansión de la vida. Tengo espacio de sobra para crecer y cambiar.'),
  ('Doy a la vida exactamente lo que quiero que ella me dé.'),
  ('A cada pensamiento negativo que me pasa por la cabeza, le digo: ¡Fuera!.'),
  ('La vida es para mí como una alegre danza.'),
  ('Mi cuerpo es ideal para mí en esta vida.'),
  ('Libero este arraigado hábito de retrasarme. Siempre llego a tiempo a todas partes.'),
  ('Mi aspecto es fabuloso y me siento fabuloso. ¡Estoy dispuesto a recibir todo lo bueno!.'),
  ('Libero todo concepto de competitividad y comparación. Hago todo lo mejor posible y disfruto siendo yo mismo.'),
  ('Todo lo que necesito saber en un momento dado se me revela. Mi intuición siempre está a mi favor.'),
  ('Ahora recibo mi bien de fuentes esperadas e inesperadas.'),
  ('Lo que quiero, lo pido. Sé que todo lo que necesite estará siempre ahí, esperándome.'),
  ('Confío en que el Poder que me ha creado me protegerá en todo momento y en toda circunstancia.'),
  ('Con alegría ayudo siempre que puedo, para aliviar las cargas de los demás.'),
  ('Me elevo por encima de toda limitación. La Divinidad me inspira y me guía. El amor sana toda la vida.'),
  ('Soy una persona especial y maravillosa. Cuanto más me amo, más libre de tensiones me siento.'),
  ('Soy una persona paciente, tolerante y afable.'),
  ('Con frecuencia expreso gratitud y reconocimiento, y espero cosas que pueda agradecer.'),
  ('Pido mayor comprensión e inteligencia, que me permitan dar forma a mi mundo y mis experiencias con conocimiento.'),
  ('Veo cómo todo lo que me rodea irradia abundancia. Vivo ahora en un amor, una luz y una felicidad sin límites.'),
  ('Me regalo amor. Hagámonos el más precioso y sanador regalo: el del amor incondicional por nosotros y por los demás.'),
  ('Gozo de todo lo que tengo y abro los brazos a todos los desafíos.'),
  ('Abro nuevas puertas a la vida. Siempre hay nuevos territorios de amor ante mí.'),
  ('Me encuentro en el lugar y el momento perfectos. Siempre estoy a salvo.'),
  ('MI vida es una fiesta, una experiencia que comparto con todas las personas que conozco.'),
  ('La vida me apoya; sólo me ofrece experiencias buenas y positivas.'),
  ('Mi búsqueda interior es gratificante y me procura muchas respuestas.'),
  ('Aprendo fácilmente y sin esfuerzo las enseñanzas de la vida.'),
  ('El amor interviene en todas mis relaciones, desde las menos importantes hasta las más íntimas.'),
  ('Mi vida empieza con gratitud y alegría.'),
  ('Este planeta es mi hogar. Amorosamente cuido de la Tierra y de todas las criaturas vivientes que la pueblan.'),
  ('Tengo siempre la edad perfecta para el momento de la vida en que me encuentro.'),
  ('Abro mi hogar, y doy la bienvenida a mis invitados con cariño y música. Par mí son como una amorosa familia.'),
  ('Estoy dispuesta a liberar las viejas creencias que ya no me sirven.'),
  ('Mi corazón perdona y libera. Con confianza me amo. La paz interior es mi objetivo.'),
  ('Toda experiencia es perfecta para mi proceso de crecimiento.'),
  ('Soy una persona organizada y productiva. Tengo mucha energía, y disfruto poniendo orden en mi vida.'),
  ('Libero todo hábito de criticar. Supero todo sentimiento de no ser una persona suficientemente capaz y creativa.'),
  ('Soy amable y paciente conmigo mientras cambio y crezco.'),
  ('Utilizo mi Sabiduría Interior para llevar los asuntos de mi vida.'),
  ('El sendero hacia el amor es el perdón. Con amor dejó atrás el pasado y concentro mi atención en este nuevo día.'),
  ('Ensancho mis fronteras con el fin de abarcar solamente experiencias positivas.'),
  ('Todos mis amigos y amigas fueron en un tiempo desconocidos para mí. Así pues, doy la bienvenida a todas las personas que se incorporan hoy a mi vida.'),
  ('La vida refleja todos mis pensamientos. Como me ocupo de que sean positivos, la vida sólo me aporta buenas experiencias.'),
  ('Me produce alegría cuidar de mí y atender a los demás.'),
  ('Yo soy la alegría de la vida, que se da y se recibe. Soy una ofrenda de amor.'),
  ('El Universo apoya totalmente todo lo que elijo pensar y creer. La paz y la armonía divinas me rodean.'),
  ('Libero y me libero. De buena gana me desprendo de todo lo que ya no necesito.'),
  ('Con pensamientos de prosperidad creo mi mundo próspero. Atraigo la prosperidad.'),
  ('Me siento a gusto en mi cuerpo. Soy salud que irradia.'),
  ('Soy independiente. Hago todo lo que quiero hacer. Pruebo nuevas ideas. Hoy soy líder.'),
  ('Bendigo a todos y a todo. Irradio alegría y la comparto con los demás.');

commit;
